---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: telco-ran-tools-storage
spec:
  capacity:
    storage: 250Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: telco-ran-tools-storage-class
  local:
    path: /dev/disk/by-partlabel/data
    fsType: xfs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: In
              values:
                - ""
